server:
  port: 9000


eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka-server-1:8761/eureka, http://eureka-server-2:8762/eureka

spring:
  application:
    name: eureka-consumer


EUREKA-PROVIDER:
  ribbon:
    NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule